[tool.poetry]
name = "synthia"
version = "0.1.0"
description = "CommuneX Validators"
authors = ["supreme <zimulajan0@gmail.com>"]
license = "MIT"
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.1"
pydantic-settings = "^2.2.1"
anthropic = "^0.21.3"
openai = "^1.14.2"
wandb = "^0.16.4"
communex = "^0.1.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
strict = ["src"]
# reportUnusedVariable = "warning"