[tool.poetry]
name = "synthia"
version = "0.1.0"
description = "CommuneX Validators"
authors = ["supreme <zimulajan0@gmail.com>"]
license = "MIT"
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.11"
communex = { git = "https://github.com/agicommies/communex.git", develop = true }
python-dotenv = "^1.0.1"
wandb = "^0.16.4"
pydentic = "^0.0.1.dev3"
openai = "^1.14.2"
pydantic-settings = "^2.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
strict = ["src"]
# reportUnusedVariable = "warning"